# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Android
      run: |
        cd VaquitApp
        nuget restore
        cd VaquitApp/VaquitApp.Android
        msbuild VaquitApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
  
  AndroidCore:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        cd VaquitApp        
        cd VaquitApp/VaquitApp.Android
        dotnet build --configuration Release --no-restore
        
  IOs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: IOs
      run: |
        cd VaquitApp
        nuget restore
        cd VaquitApp/VaquitApp.IOS
        msbuild VaquitApp.IOS.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
